version: "3"
services:

  bdd:
    build: 
      context: .
      dockerfile: postgis.Dockerfile
    image: rok4/postgis-tests

    environment:
      - POSTGRES_DB=ign
      - POSTGRES_USER=ign
      - POSTGRES_PASSWORD=ign

  fullgeneration:
    build: 
      context: .
      dockerfile: fullgeneration.Dockerfile
    image: rok4/fullgeneration-tests
    volumes:
      - common:/common
      - scripts:/scripts
      - pyramids:/pyramids

volumes:
  common:
  scripts:
  pyramids: