version: "3"
services:

  middle:
    image: rok4/server:${TAG}
    volumes:
      - ./pyramids.tar:/pyramids.tar:ro
    command: bash -c "tar -x -f /pyramids.tar --directory /pyramids/ && /bin/rok4 -f /etc/rok4/server.json"

  front:
    image: nginx:alpine
    links:
      - middle
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    depends_on:
      - middle

  tests:
    build: .
    image: rok4/server-tests
    depends_on:
      - front


