version: "3"
services:

  storage:
    image: rok4/dataset:minio

  middle:
    image: rok4/server:${TAG}
    environment:
      - ROK4_S3_SECRETKEY=rok4S3storage
      - ROK4_S3_KEY=rok4
      - ROK4_S3_URL=http://storage:9000
    depends_on:
      - storage

  front:
    image: nginx:alpine
    links:
      - middle
    volumes:
      - ./default.conf.template:/etc/nginx/templates/default.conf.template
    depends_on:
      - middle

  tests:
    build: .
    image: rok4/server-tests
    depends_on:
      - front


