version: "3"
services:

  bdd:
    build: 
      context: .
      dockerfile: postgis.Dockerfile
    image: rok4/postgis-tests

    environment:
      - POSTGRES_DB=ign
      - POSTGRES_USER=ign
      - POSTGRES_PASSWORD=ign

  pregeneration:
    build: 
      context: .
      dockerfile: pregeneration.Dockerfile
    image: rok4/pregeneration-tests
    volumes:
      - common:/common
      - scripts:/scripts
      - pyramids:/pyramids

  generation:
    build: 
      context: .
      dockerfile: generation.Dockerfile
    image: rok4/generation-tests
    volumes:
      - common:/common
      - scripts:/scripts
      - pyramids:/pyramids

volumes:
  common:
  scripts:
  pyramids: